### PR TITLE
Send the excel file via Email

### PR DESCRIPTION
**Pull request by RakiZtahX**
Is there a way to send the downloaded file via email? I using this in our WordPress and I just need to send it via wp_mail

### CODE REVIEW

**Comment by shuchkin** [comment]
use actual version pls

**Comment by RakiZtahX** [comment]
<?php 
	include 'wp-load.php';    
    
	if (isset($_POST['array2excel'])) {		
		
		$title = $_POST['title'];  
        
		$plugin_dir = '/home/content/public_html/wp-content/plugins/worders/public/lib/simplexlsgen/autoload.php';
		require_once ( $plugin_dir );
        
         $data = json_decode($_POST['array2excel'], false);
		\Shuchkin\SimpleXLSXGen::fromArray($data)
		->setDefaultFont('Roboto')
		->setDefaultFontSize(12) 
		->saveAs('temp.xlsx');
		
		
		wp_mail( 'sigfred.chamo@gmail.com', 'test xlsx', 'see attachments', [], 'temp.xlsx' );
		
		$data = json_decode($_POST['array2excel'], false);
		\Shuchkin\SimpleXLSXGen::fromArray($data)
		->setDefaultFont('Roboto')
		->setDefaultFontSize(12) 
		->downloadAs($title . '.xlsx');
		
		return;	  
        
	}	


?>

this is the array2excel file. I used ajax and there's an error 403. I want download it and sent it in email. without the email part its working. kindly help me

**Comment by shuchkin** [comment]
may be current folder is read only, check linux rights or replace ```'temp.xlsx'``` to ```get_temp_dir() . 'temp.xlsx'``` in saveAs and wp_mail

**Comment by RakiZtahX** [comment]
`<?php 
	include 'wp-load.php';    
    
	if (isset($_POST['array2excel'])) {		
		
		$title = $_POST['title'];  
        
		$plugin_dir = '/home/content/public_html/wp-content/plugins/worders/public/lib/simplexlsgen/autoload.php';
		require_once ( $plugin_dir );		
		
		
		$data = json_decode($_POST['array2excel'], false);
		\Shuchkin\SimpleXLSXGen::fromArray($data)
		->setDefaultFont('Roboto')
		->setDefaultFontSize(12) 
		->saveAs($title . '.xlsx');  
        
        $file = get_temp_dir() . $title . '.xlsx';
        
        wp_mail( 'sigfred.chamo@gmail.com', 'test xlsx', 'see attachments', [], $file );
		
		return;	  
        
	}	


?>`

This is the updated code but it still returns Error: 403.

**Comment by RakiZtahX** [comment]
`$data = [[1, 2, 3]];
	\Shuchkin\SimpleXLSXGen::fromArray($data)
	->setDefaultFont('Roboto')
	->setDefaultFontSize(12) 
	->saveAs('temp.xlsx');

	echo get_temp_dir();`

https://contentwarehouse.net/array2excel.php

I already directly put the code there.
Please help me. I don't see the temp.xlsx. Where can I see the file created when it saveAs?

**Comment by RakiZtahX** [comment]
I got it. Thanks

**Pull request closed without merging**
