### PR TITLE
Added Font Color and Background Color Capabilities

### PR DESCRIPTION
**Pull request by mrjemson**
Added capability to set font colors in cells.
Probably more elegant ways to achieve this, but working well in my testing.
Updated Readme and screenshot for the same.

### CODE REVIEW

**Comment by shuchkin** [comment]
good work, but i don't like additianal tags with attrs for advanced stuffs
may be one tag `style`
```
<style color="#FFFFFF" bgcolor="#000000">White text on black background</style>
```
next iteration
```
<style color="#FFFFFF" font="Arial" bgcolor="#000000" bgfill="dashed">White Arial text on black dashed bg</style>
```

**Comment by mrjemson** [comment]
Sure, we could switch to a style tag.
Makes sense and also keeps the flexibility of being able to use any hex value for the colour without forcing users into canned tag options <red> <green> etc
I will update it sometime today.

**Comment by mrjemson** [comment]
@shuchkin I have updated to style tags as discussed :)

**Comment by shuchkin** [comment]
super!

**Comment by shuchkin** [comment]
I've rewrited `style` support code, see 1.2.10

**Pull request merged**
